---
###
# dont't forget to define environment variables 
#  ${BASE_DIR}
#  ${BINDS}
#  ${WEB_PORT}
###
#version: "2"
services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - ${BASE_DIR}/${BINDS}/homer/_data/:/www/assets
    ports:
      - ${WEB_PORT}:8080      
    #environment:
    #  - UID=1000
    #  - GID=1000
    #  - INIT_ASSETS=1 # default
    restart: unless-stopped
